netbackupkops:
  containers:
    manager:
      image: asia-southeast2-docker.pkg.dev/joey-dev-project/dev-veritas/netbackupkops:netbackupkops_10.4_0018
      resources:
        limits:
          cpu: 150m
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 500Mi
  kopsPvcStorageClass:
  kopsPvcSize: 10Gi
  pvMountPath: /usr/openv
  imagePullSecrets: 
  - name: netbackupkops-docker-creds
  fipsMode: DISABLE
  acceleratorTracklogPvcStorageClass: None
nbsetup:
  replicas: 1
  containers:
    netbackup_config_pod:
      nbprimaryserver: dev-id-veritas-media-server-instance-01
      nbsha256fingerprint: 9F:42:40:81:62:CF:0A:B1:75:A1:46:E0:51:BC:E9:CA:86:E1:05:D9:F6:17:95:AD:85:23:EF:66:CD:1D:6F:2B
      k8sCluster: dev-id-bks-gke-02
      k8sPort: 6443
      datamoverimage: asia-southeast2-docker.pkg.dev/joey-dev-project/dev-veritas/netbackupdatamover:dev-10.4
      logLevel: INFO
      storageclassblock: standard-rwo
      volumesnapshotclassblock: csi-pd-hostpath-snapclass
      storageclassfilesystem: standard-rwo
      volumesnapshotclassfilesystem: csi-pd-hostpath-snapclass
