apiVersion: v1
kind: Secret
metadata:
  name: netbackup-1-nb-config-deploy-secret
  namespace: netbackup-1
type: Opaque
stringData:
  apikey: AxCbN8iDc6rDk9RjD5DEZ4VxINhr8YHfRwRGSVRSD5TpFGydAGiUF2a-2sPtD991
